loader:
  name: 'synthetic'
  batch_size: 4
  batches_in_epoch: 1024
  start_epoch: 1
  epochs: 200000
  num_workers: 4
  size: [120, 160]

  primitives: [
    'lines',
    'polygon',
    'ellipses',
    'star',
    'stripes',
    'cube',
    'checkerboard'
  ]

  homography:
    patch: {ratio: 0.5}
    perspective: {prob: 0.5, dx: 0.05, dy: 0.05, artifacts: False}
    rotation: {prob: 0.5, max_angle: 1.57, num_angles: 10, artifacts: False}

  augmentation:
    gaussian_noise: {prob: 0.5, stddev: [0.5, 0.95]}
    speckle_noise: {prob: 1, stddev: [.0, .005]}


model:
    name: 'superpoint'
    detector: true
    descriptor: false
