loader:
  name: 'synthetic'
  batch_size: 4
  batches_in_epoch: 1024
  start_epoch: 1
  epochs: 200000
  num_workers: 4
  size: [120, 160]

  primitives:
    'background': {size: [960, 1280]}
    'primitives': [
      'lines',
      'polygon',
      'ellipses',
      'star',
      'stripes',
      'cube',
      'checkerboard'
    ]

  homography:
    patch: {ratio: 0.5}
    perspective: {prob: 0.5, dx: 0.2, dy: 0.2, artifacts: True}
    rotation: {prob: 0.5, max_angle: 1.57, num_angles: 90, artifacts: True}
    scaling: {prob: 0.5, scale: 0.2, num_scales: 10, std: 2, artifacts: True}
    translation: {prob: 0.5, overflow: 0, artifacts: True}

  augmentation:
    gaussian_noise: {prob: 0.5, stddev: [0, 15]}
    speckle_noise: {prob: 0.5, range: [0, 0.0035]}
    random_brightness: {prob: 0.5, max_change: 75}
    random_contrast: {prob: 0.5, range: [0.5, 1.8]}
    additive_shade: {prob: 0.5, ellipses: 10, transparency: [0.9, 1], ksize: [50, 100]}
    motion_blur: {prob: 0.5, ksize: 22}

model:
    name: 'superpoint'
    detector: true
    descriptor: false
